print("To Live\nis\nTo Suffer")
print("cool\\n function is great")
print("print\mehquote")
print("backslash power\ ok")
print("Phrase power\Phrase_=_\"whatever you choose")
phrase = "backslash power"
print(phrase)
print("Here is concatenation")
print(phrase + " is cool")
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print(phrase)
print("The len function is the length function conveying total charcters in a string")
print("\len(phrase)")
print(len(phrase))
print(phrase[4])
print(phrase.index("h"))
print(phrase.index("pow"))
print(phrase.index("p"))
print(phrase[10])
print(phrase[11])
print("In python, length calculations begin from 0 and incude spaces thoughout. [5] (phrase.index(\"p\").")
print(phrase.replace("power", "glory"))
print(phrase + "is way better")
print(phrase + " is way better")
print(phrase + "is way better\nfrom whence\nthee came but ultimatley + (phrase.upper()")
print(phrase + "is way better\nfrom whence\nthee came but ultimatley but (phrase).")